name: model-validation
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - nextflow
  - pyvista
  - meshio
  - yaml
  - rdflib
  - matplotlib
  - conda-lock
  - conda
  - pip
  - pip:
      - "--editable=git+https://github.com/izus-fokus/snakemake-report-plugin-metadata4ing.git#egg=snakemake-report-plugin-metadata4ing"