name: model-validation-platform-docs
channels:
  - conda-forge
dependencies:
  - mkdocs
  - mkdocs-bibtex
  - python-markdown-math
  - mkdocs-jupyter
  #- markdown-checklist
  - pymdown-extensions
  - pip:
    - mkdocs-include-dir-to-nav


