name: model-validation
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - nextflow
  - pyvista
  - meshio
  - conda-lock
  - conda
  - pip
  - pip:
      - "--editable=git+https://github.com/M-Jafarkhani/snakemake-report-plugin-metadata4ing.git#egg=snakemake-report-plugin-metadat4ing"