site_name: NFDI4Ing Model Validation Platform

repo_url: https://github.com/BAMresearch/NFDI4IngModelValidationPlatform

theme:
  name: readthedocs
  highlightjs: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - search
  - bibtex:
      bib_file: "docs/literature.bib"

markdown_extensions:
#  - markdown_include.include:
#      base_path: .
  - admonition
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
